### ISSUE TITLE
Repetetive calling of GetPlayers() causes issue since no new challenge response is returned but instead already player response

### ISSUE THREAD

**Issue by dabo123148** [Florian2406/Okolni-Source-Ouery#4] opened 2020-12-30 02:26 UTC
Calling of GetPlayers() multiple times after each other for the same server (within a minute) causes exception "Response was no challenge response."
This is since there is no new challenge-response returned(tested with ark servers), making
 if (!byteReader.GetByte().Equals(0x41))
                    throw new ArgumentException("Response was no challenge response.");
                req[5] = byteReader.GetByte();
                req[6] = byteReader.GetByte();
                req[7] = byteReader.GetByte();
                req[8] = byteReader.GetByte();
                request(req);
                response = fetchResponse();
                byteReader = response.GetByteReader();
byte header = byteReader.GetByte();
unnessesary for repetitive requests since it is already a player response. Thus with a small change to those lines can avoid that issue

**Comment by Florian2406** [comment] 2020-12-31 10:31
Thanks for your feedback, I will have a closer look when I return home in a few days.

**Comment by Florian2406** [comment] 2021-01-05 19:20
The issue is now fixed, also for the GetRules method where the same error occured. I implemented a check whether or not the repsonse is a challenge response at the position you suggested.

The minimum nuget package version for the fix is **1.0.0**

**Closed as completed by Florian2406** 2021-01-05 19:20 UTC
Labels: bug
