### ISSUE TITLE
player.Index not working

### ISSUE THREAD

**Issue by dani142c** [Florian2406/Okolni-Source-Ouery#5] opened 2021-07-06 17:28 UTC
I'm trying to get the Index of players on the server, using the following code:

```
         public static void IndexPlayers(Server server)
        {
            IQueryConnection con = new QueryConnection();

            con.Host = server.IP;
            con.Port = server.Port;
            con.Connect();

            var players = con.GetPlayers();
            var newPlayers = players.Players.ToArray();

            foreach (var player in newPlayers)
            {
                Console.WriteLine(player.Index);
            }
        }
```
        
 All I get is 0, 0, and so on. I don't get any unique ID. Even If i don't convert it to an array, I still get the same response:
 
 `Console.WriteLine(players.Players[3].Index);`

**Comment by Florian2406** [comment] 2021-07-07 06:00
I'll start investigating

**Comment by Florian2406** [comment] 2021-07-07 20:29
The issue is probably not in the library afaik. I tried to check with my server and also random servers but i couldn't actually find any server that really uses the index. It seems as if it is always 0 for everyone.

Can you add an example where it should come with the ids? Maybe an ip/port-combination so i can verify the bytes returned by it.

**Comment by Florian2406** [comment] 2021-09-21 10:37
Closed as there probably is no issue in the library. Investigated the returned response on byte level and i couldn't find any server that actually uses the index.

**Closed as completed by Florian2406** 2021-09-21 10:37 UTC
